import type { Metadata } from "next";
import "./globals.css";
import { hanseokbong } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={hanseokbong.variable}>
      <body className={hanseokbong.className}>{children}</body>
    </html>
  );
}
